language: verilog

services:
  - docker

before_install:
  - docker build -t icarus-verilog .

jobs:
  include:
    - stage: unit tests                # naming the Tests stage
      name: "Arithmeticologic Tests"            # names the first Tests stage job
      script: docker run icarus-verilog /bin/sh -c "iverilog -o bin/al tb/arithmeticologic.v ; bin/al;"
    - stage: unit tests                # naming the Tests stage
      name: "Integration Tests"     # names the second Tests stage job
      script: docker run icarus-verilog /bin/sh -c "iverilog -o bin/ls tb/load_store.v ; bin/ls;"
